<?php

return [
    [
        'key' => 'lotto',
        'name' => 'Lotto',
        'route' => 'admin.lotto.draws.index',
        'sort' => 87,
    ],
    [
        'key' => 'lotto.zone',
        'name' => 'Lotto Zone',
        'route' => 'admin.lotto.draws.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto.zone.draws',
        'name' => 'งวดหวย',
        'route' => 'admin.lotto.draws.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto.zone.tickets',
        'name' => 'รายการแทง',
        'route' => 'admin.lotto.tickets.index',
        'sort' => 2,
    ],
    [
        'key' => 'lotto.settings',
        'name' => 'ตั้งค่า Lotto',
        'route' => 'admin.lotto.switches.index',
        'sort' => 2,
    ],
    [
        'key' => 'lotto.settings.switches',
        'name' => 'เปิด-ปิด หวย',
        'route' => 'admin.lotto.switches.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto.settings.number_blocks',
        'name' => 'เลขอั้น',
        'route' => 'admin.lotto.number_blocks.index',
        'sort' => 2,
    ],
    [
        'key' => 'lotto.settings.groups',
        'name' => 'กลุ่มหวย',
        'route' => 'admin.lotto.groups.index',
        'sort' => 3,
    ],
    [
        'key' => 'lotto.settings.markets',
        'name' => 'รายการหวย',
        'route' => 'admin.lotto.markets.index',
        'sort' => 4,
    ],
    [
        'key' => 'lotto.settings.bet_types',
        'name' => 'ประเภทหวย',
        'route' => 'admin.lotto.settings.bet_types',
        'sort' => 5,
    ],
    [
        'key' => 'lotto.settings.payout_settings',
        'name' => 'ตั้งค่า อัตราจ่าย',
        'route' => 'admin.lotto.rate_plans.index',
        'sort' => 6,
    ],
    [
        'key' => 'lotto.settings.bet_limit_settings',
        'name' => 'ขั้นต่ำ/สูงสุด/สูงสุดต่อเลข',
        'route' => 'admin.lotto.bet_limits.index',
        'sort' => 7,
    ],
    [
        'key' => 'lotto.reports',
        'name' => 'รายงาน Lotto',
        'route' => 'admin.lotto.reports.pending_bets',
        'sort' => 3,
    ],
    [
        'key' => 'lotto.reports.pending_bets',
        'name' => 'รอผลเดิมพัน',
        'route' => 'admin.lotto.reports.pending_bets',
        'sort' => 1,
    ],
    [
        'key' => 'lotto.reports.profit_loss_forecast',
        'name' => 'ดูของรวม/คาดคะเน ได้-เสีย',
        'route' => 'admin.lotto.reports.profit_loss_forecast',
        'sort' => 2,
    ],
    [
        'key' => 'lotto.reports.member_bet_types',
        'name' => 'ดูของสมาชิก/ประเภท',
        'route' => 'admin.lotto.reports.member_bet_types',
        'sort' => 3,
    ],
    [
        'key' => 'lotto.reports.tickets_cancel',
        'name' => 'รายการโพย/ยกเลิกโพย',
        'route' => 'admin.lotto.reports.tickets_cancel',
        'sort' => 4,
    ],
    [
        'key' => 'lotto.reports.blocked_numbers',
        'name' => 'เลขปิดรับ/เลขอั้น',
        'route' => 'admin.lotto.reports.blocked_numbers',
        'sort' => 5,
    ],

    // Legacy-compatible ACL keys for CRUD actions.
    [
        'key' => 'lotto.groups',
        'name' => 'กลุ่มหวย',
        'route' => 'admin.lotto.groups.index',
        'sort' => 10,
    ],
    [
        'key' => 'lotto.groups.create',
        'name' => 'เพิ่มกลุ่มหวย',
        'route' => 'admin.lotto.groups.create',
        'sort' => 11,
    ],
    [
        'key' => 'lotto.groups.update',
        'name' => 'แก้ไขกลุ่มหวย',
        'route' => 'admin.lotto.groups.update',
        'sort' => 12,
    ],
    [
        'key' => 'lotto.markets',
        'name' => 'รายการหวย',
        'route' => 'admin.lotto.markets.index',
        'sort' => 15,
    ],
    [
        'key' => 'lotto.markets.create',
        'name' => 'เพิ่มรายการหวย',
        'route' => 'admin.lotto.markets.create',
        'sort' => 16,
    ],
    [
        'key' => 'lotto.markets.update',
        'name' => 'แก้ไขรายการหวย',
        'route' => 'admin.lotto.markets.update',
        'sort' => 17,
    ],
    [
        'key' => 'lotto.rate_plans',
        'name' => 'อัตราจ่าย',
        'route' => 'admin.lotto.rate_plans.index',
        'sort' => 20,
    ],
    [
        'key' => 'lotto.rate_plans.load_market',
        'name' => 'ดูอัตราจ่ายรายตลาด',
        'route' => 'admin.lotto.rate_plans.load_market',
        'sort' => 21,
    ],
    [
        'key' => 'lotto.rate_plans.update_market',
        'name' => 'แก้ไขอัตราจ่ายรายตลาด',
        'route' => 'admin.lotto.rate_plans.update_market',
        'sort' => 22,
    ],
    [
        'key' => 'lotto.default_settings',
        'name' => 'ค่าพื้นฐานหวย',
        'route' => 'admin.lotto.default_settings.index',
        'sort' => 23,
    ],
    [
        'key' => 'lotto.default_settings.create',
        'name' => 'เพิ่มค่าพื้นฐานหวย',
        'route' => 'admin.lotto.default_settings.create',
        'sort' => 24,
    ],
    [
        'key' => 'lotto.default_settings.update',
        'name' => 'แก้ไขค่าพื้นฐานหวย',
        'route' => 'admin.lotto.default_settings.update',
        'sort' => 25,
    ],
    [
        'key' => 'lotto.bet_limits',
        'name' => 'ขั้นต่ำ/สูงสุด/สูงสุดต่อเลข',
        'route' => 'admin.lotto.bet_limits.index',
        'sort' => 26,
    ],
    [
        'key' => 'lotto.bet_limits.load_market',
        'name' => 'ดูค่าขั้นต่ำ/สูงสุดรายตลาด',
        'route' => 'admin.lotto.bet_limits.load_market',
        'sort' => 27,
    ],
    [
        'key' => 'lotto.bet_limits.update_market',
        'name' => 'แก้ไขค่าขั้นต่ำ/สูงสุดรายตลาด',
        'route' => 'admin.lotto.bet_limits.update_market',
        'sort' => 28,
    ],
    [
        'key' => 'lotto.member_permissions',
        'name' => 'สิทธิ์การเล่น',
        'route' => 'admin.lotto.member_permissions.index',
        'sort' => 29,
    ],
    [
        'key' => 'lotto.member_permissions.create',
        'name' => 'เพิ่มสิทธิ์การเล่น',
        'route' => 'admin.lotto.member_permissions.create',
        'sort' => 24,
    ],
    [
        'key' => 'lotto.member_permissions.update',
        'name' => 'แก้ไขสิทธิ์การเล่น',
        'route' => 'admin.lotto.member_permissions.update',
        'sort' => 25,
    ],
    [
        'key' => 'lotto.draws',
        'name' => 'งวดหวย',
        'route' => 'admin.lotto.draws.index',
        'sort' => 26,
    ],
    [
        'key' => 'lotto.draws.create',
        'name' => 'เพิ่มงวดหวย',
        'route' => 'admin.lotto.draws.create',
        'sort' => 27,
    ],
    [
        'key' => 'lotto.draws.update',
        'name' => 'แก้ไขงวดหวย',
        'route' => 'admin.lotto.draws.update',
        'sort' => 28,
    ],
    [
        'key' => 'lotto.draws.open',
        'name' => 'เปิดรับงวดหวย',
        'route' => 'admin.lotto.draws.open',
        'sort' => 29,
    ],
    [
        'key' => 'lotto.draws.close',
        'name' => 'ปิดรับงวดหวย',
        'route' => 'admin.lotto.draws.close',
        'sort' => 30,
    ],
    [
        'key' => 'lotto.draws.settle',
        'name' => 'ประกาศผลงวดหวย',
        'route' => 'admin.lotto.draws.settle',
        'sort' => 31,
    ],
    [
        'key' => 'lotto.draws.generate_auto',
        'name' => 'สร้างงวดอัตโนมัติ',
        'route' => 'admin.lotto.draws.generate_auto',
        'sort' => 32,
    ],
    [
        'key' => 'lotto.number_blocks',
        'name' => 'เลขอั้น',
        'route' => 'admin.lotto.number_blocks.index',
        'sort' => 32,
    ],
    [
        'key' => 'lotto.number_blocks.create',
        'name' => 'เพิ่มเลขอั้น',
        'route' => 'admin.lotto.number_blocks.create',
        'sort' => 33,
    ],
    [
        'key' => 'lotto.number_blocks.update',
        'name' => 'แก้ไขเลขอั้น',
        'route' => 'admin.lotto.number_blocks.update',
        'sort' => 34,
    ],
    [
        'key' => 'lotto.tickets',
        'name' => 'รายการแทง',
        'route' => 'admin.lotto.tickets.index',
        'sort' => 35,
    ],
    [
        'key' => 'lotto.tickets.loaddata',
        'name' => 'ดูรายละเอียดโพย',
        'route' => 'admin.lotto.tickets.loaddata',
        'sort' => 36,
    ],
];
