<?php

return [
    [
        'key' => 'lotto_tickets',
        'name' => 'รายการโพย',
        'route' => 'admin.lotto.tickets.index',
        'sort' => 35,
    ],
    [
        'key' => 'lotto_settings',
        'name' => 'ตั้งค่าหวย',
        'route' => 'admin.lotto.switches.index',
        'sort' => 88,
    ],
    [
        'key' => 'lotto_settings.draws',
        'name' => 'งวดหวย',
        'route' => 'admin.lotto.draws.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.draws.index',
        'name' => 'เห็นเมนู งวดหวย',
        'route' => 'admin.lotto.draws.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.draws.create',
        'name' => 'สิทธิ์ เพิ่มข้อมูล งวดหวย',
        'route' => 'admin.lotto.draws.create',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.draws.update',
        'name' => 'สิทธิ์ แก้ไขข้อมูล งวดหวย',
        'route' => 'admin.lotto.draws.update',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_settings.draws.open',
        'name' => 'สิทธิ์ เปิดรับงวดหวย',
        'route' => 'admin.lotto.draws.open',
        'sort' => 4,
    ],
    [
        'key' => 'lotto_settings.draws.force_open',
        'name' => 'สิทธิ์ เปิดรับก่อนเวลา',
        'route' => 'admin.lotto.draws.open',
        'sort' => 5,
    ],
    [
        'key' => 'lotto_settings.draws.close',
        'name' => 'สิทธิ์ ปิดรับงวดหวย',
        'route' => 'admin.lotto.draws.close',
        'sort' => 6,
    ],
    [
        'key' => 'lotto_settings.draws.settle',
        'name' => 'สิทธิ์ ประกาศผลงวดหวย',
        'route' => 'admin.lotto.draws.settle',
        'sort' => 7,
    ],
    [
        'key' => 'lotto_settings.draws.cancel_all_refund',
        'name' => 'สิทธิ์ ยกเลิกโพยทั้งงวดและคืนเงิน',
        'route' => 'admin.lotto.draws.cancel_all_refund',
        'sort' => 8,
    ],
    [
        'key' => 'lotto_settings.draws.mark_no_result',
        'name' => 'สิทธิ์ ระบุงดออกผลงวดหวย',
        'route' => 'admin.lotto.draws.mark_no_result',
        'sort' => 9,
    ],
    [
        'key' => 'lotto_settings.draws.auto_result_test_fetch',
        'name' => 'สิทธิ์ ทดสอบดึงผลอัตโนมัติ',
        'route' => 'admin.lotto.draws.auto_result_test_fetch',
        'sort' => 10,
    ],
    [
        'key' => 'lotto_settings.draws.auto_result_manual_retry',
        'name' => 'สิทธิ์ ลองดึงผลอัตโนมัติใหม่',
        'route' => 'admin.lotto.draws.auto_result_manual_retry',
        'sort' => 11,
    ],
    [
        'key' => 'lotto_settings.draws.auto_result_metrics',
        'name' => 'สิทธิ์ ดูสถิติผลอัตโนมัติ',
        'route' => 'admin.lotto.draws.auto_result_metrics',
        'sort' => 12,
    ],
    [
        'key' => 'lotto_settings.draws.auto_result_logs',
        'name' => 'สิทธิ์ ดูบันทึกผลอัตโนมัติ',
        'route' => 'admin.lotto.draws.auto_result_logs',
        'sort' => 13,
    ],
    [
        'key' => 'lotto_settings.switches',
        'name' => 'เปิด-ปิด หวย',
        'route' => 'admin.lotto.switches.index',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.number_blocks',
        'name' => 'เลขอั้น',
        'route' => 'admin.lotto.number_blocks.index',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_settings.number_blocks.index',
        'name' => 'เห็นเมนู เลขอั้น',
        'route' => 'admin.lotto.number_blocks.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.number_blocks.create',
        'name' => 'สิทธิ์ เพิ่มข้อมูล เลขอั้น',
        'route' => 'admin.lotto.number_blocks.create',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.number_blocks.update',
        'name' => 'สิทธิ์ แก้ไขข้อมูล เลขอั้น',
        'route' => 'admin.lotto.number_blocks.update',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_settings.number_blocks.delete',
        'name' => 'สิทธิ์ ลบข้อมูล เลขอั้น',
        'route' => 'admin.lotto.number_blocks.delete',
        'sort' => 4,
    ],
    [
        'key' => 'lotto_settings.groups',
        'name' => 'กลุ่มหวย',
        'route' => 'admin.lotto.groups.index',
        'sort' => 4,
    ],
    [
        'key' => 'lotto_settings.groups.index',
        'name' => 'เห็นเมนู กลุ่มหวย',
        'route' => 'admin.lotto.groups.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.groups.create',
        'name' => 'สิทธิ์ เพิ่มข้อมูล กลุ่มหวย',
        'route' => 'admin.lotto.groups.create',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.groups.update',
        'name' => 'สิทธิ์ แก้ไขข้อมูล กลุ่มหวย',
        'route' => 'admin.lotto.groups.update',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_settings.markets',
        'name' => 'รายการหวย',
        'route' => 'admin.lotto.markets.index',
        'sort' => 5,
    ],
    [
        'key' => 'lotto_settings.markets.index',
        'name' => 'เห็นเมนู รายการหวย',
        'route' => 'admin.lotto.markets.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.markets.create',
        'name' => 'สิทธิ์ เพิ่มข้อมูล รายการหวย',
        'route' => 'admin.lotto.markets.create',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.markets.update',
        'name' => 'สิทธิ์ แก้ไขข้อมูล รายการหวย',
        'route' => 'admin.lotto.markets.update',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_settings.group_packages',
        'name' => 'แพ็กเกจกลุ่มหวย',
        'route' => 'admin.lotto.group_packages.index',
        'sort' => 6,
    ],
    [
        'key' => 'lotto_settings.group_packages.index',
        'name' => 'เห็นเมนู แพ็กเกจกลุ่มหวย',
        'route' => 'admin.lotto.group_packages.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.group_packages.create',
        'name' => 'สิทธิ์ เพิ่มข้อมูล แพ็กเกจกลุ่มหวย',
        'route' => 'admin.lotto.group_packages.create',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.group_packages.update',
        'name' => 'สิทธิ์ แก้ไขข้อมูล แพ็กเกจกลุ่มหวย',
        'route' => 'admin.lotto.group_packages.update',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_settings.group_packages.delete',
        'name' => 'สิทธิ์ ลบข้อมูล แพ็กเกจกลุ่มหวย',
        'route' => 'admin.lotto.group_packages.delete',
        'sort' => 4,
    ],
    [
        'key' => 'lotto_settings.bet_limit_settings',
        'name' => 'ขั้นต่ำ/สูงสุด/สูงสุดต่อเลข',
        'route' => 'admin.lotto.bet_limits.index',
        'sort' => 7,
    ],
    [
        'key' => 'lotto_settings.bet_limit_settings.index',
        'name' => 'เห็นเมนู ขั้นต่ำ/สูงสุด/สูงสุดต่อเลข',
        'route' => 'admin.lotto.bet_limits.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.bet_limit_settings.update',
        'name' => 'สิทธิ์ แก้ไขข้อมูล ขั้นต่ำ/สูงสุด/สูงสุดต่อเลข',
        'route' => 'admin.lotto.bet_limits.update_market',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.navbar_configs',
        'name' => 'Navbar Config',
        'route' => 'admin.lotto.navbar_configs.index',
        'sort' => 8,
    ],
    [
        'key' => 'lotto_settings.navbar_configs.index',
        'name' => 'เห็นเมนู Navbar Config',
        'route' => 'admin.lotto.navbar_configs.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.navbar_configs.create',
        'name' => 'สิทธิ์ เพิ่มข้อมูล Navbar Config',
        'route' => 'admin.lotto.navbar_configs.create',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_settings.navbar_configs.update',
        'name' => 'สิทธิ์ แก้ไขข้อมูล Navbar Config',
        'route' => 'admin.lotto.navbar_configs.update',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_settings.navbar_configs.delete',
        'name' => 'สิทธิ์ ลบข้อมูล Navbar Config',
        'route' => 'admin.lotto.navbar_configs.delete',
        'sort' => 4,
    ],
    [
        'key' => 'lotto_settings.navbar_configs.publish',
        'name' => 'สิทธิ์ Publish Navbar Config',
        'route' => 'admin.lotto.navbar_configs.publish',
        'sort' => 5,
    ],
    [
        'key' => 'lotto_settings.navbar_configs.unpublish',
        'name' => 'สิทธิ์ Unpublish Navbar Config',
        'route' => 'admin.lotto.navbar_configs.unpublish',
        'sort' => 6,
    ],
    [
        'key' => 'lotto_settings.frontend_theme',
        'name' => 'Frontend Theme',
        'route' => 'admin.lotto.frontend_theme.index',
        'sort' => 9,
    ],
    [
        'key' => 'lotto_settings.frontend_theme.index',
        'name' => 'เห็นเมนู Frontend Theme',
        'route' => 'admin.lotto.frontend_theme.index',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_settings.frontend_theme.update',
        'name' => 'สิทธิ์ แก้ไข Frontend Theme',
        'route' => 'admin.lotto.frontend_theme.update',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_reports',
        'name' => 'รายงาน Lotto',
        'route' => 'admin.lotto.reports.pending_bets',
        'sort' => 89,
    ],
    [
        'key' => 'lotto_reports.pending_bets',
        'name' => 'รอผลเดิมพัน',
        'route' => 'admin.lotto.reports.pending_bets',
        'sort' => 1,
    ],
    [
        'key' => 'lotto_reports.profit_loss_forecast',
        'name' => 'ดูของรวม/คาดคะเน ได้-เสีย',
        'route' => 'admin.lotto.reports.profit_loss_forecast',
        'sort' => 2,
    ],
    [
        'key' => 'lotto_reports.member_bet_types',
        'name' => 'ดูของสมาชิก/ประเภท',
        'route' => 'admin.lotto.reports.member_bet_types',
        'sort' => 3,
    ],
    [
        'key' => 'lotto_reports.tickets_cancel',
        'name' => 'รายการโพย/ยกเลิกโพย',
        'route' => 'admin.lotto.reports.tickets_cancel',
        'sort' => 4,
    ],
    [
        'key' => 'lotto_reports.blocked_numbers',
        'name' => 'เลขปิดรับ/เลขอั้น',
        'route' => 'admin.lotto.reports.blocked_numbers',
        'sort' => 5,
    ],
    [
        'key' => 'lotto_reports.results_by_date',
        'name' => 'ดูผลรางวัลทั้งหมด',
        'route' => 'admin.lotto.reports.results_by_date',
        'sort' => 6,
    ],
    [
        'key' => 'lotto_reports.winning_report',
        'name' => 'ดูรายงานผลชนะ',
        'route' => 'admin.lotto.winning_report.index',
        'sort' => 7,
    ],
    [
        'key' => 'lotto_reports.winning_report.export',
        'name' => 'ส่งออกรายงานผลชนะ',
        'route' => 'admin.lotto.winning_report.export',
        'sort' => 8,
    ],
    [
        'key' => 'lotto.yeekee.audit.view',
        'name' => 'สิทธิ์ ดู Yeekee Audit (ข้อมูล masked)',
        'route' => 'admin.lotto.yeekee.audit.rounds',
        'sort' => 90,
    ],
    [
        'key' => 'lotto.yeekee.audit.view_sensitive',
        'name' => 'สิทธิ์ ดู Yeekee Audit ข้อมูล Sensitive (Snapshot / IP / Raw)',
        'route' => 'admin.lotto.yeekee.audit.rounds',
        'sort' => 91,
    ],
];
