<?php

return [
    [
        'key' => 'lotto',
        'name' => 'Lotto',
        'route' => 'admin.lotto.draws.index',
        'sort' => 87,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.zone',
        'name' => 'Lotto Zone',
        'route' => 'admin.lotto.draws.index',
        'sort' => 1,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.zone.draws',
        'name' => 'งวดหวย',
        'route' => 'admin.lotto.draws.index',
        'sort' => 1,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.zone.tickets',
        'name' => 'รายการแทง',
        'route' => 'admin.lotto.tickets.index',
        'sort' => 2,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings',
        'name' => 'ตั้งค่า Lotto',
        'route' => 'admin.lotto.switches.index',
        'sort' => 2,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings.switches',
        'name' => 'เปิด-ปิด หวย',
        'route' => 'admin.lotto.switches.index',
        'sort' => 1,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings.number_blocks',
        'name' => 'เลขอั้น',
        'route' => 'admin.lotto.number_blocks.index',
        'sort' => 2,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings.groups',
        'name' => 'กลุ่มหวย',
        'route' => 'admin.lotto.groups.index',
        'sort' => 3,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings.markets',
        'name' => 'รายการหวย',
        'route' => 'admin.lotto.markets.index',
        'sort' => 4,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings.bet_types',
        'name' => 'ประเภทหวย',
        'route' => 'admin.lotto.settings.bet_types',
        'sort' => 5,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings.payout_settings',
        'name' => 'ตั้งค่า อัตราจ่าย',
        'route' => 'admin.lotto.rate_plans.index',
        'sort' => 6,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.settings.bet_limit_settings',
        'name' => 'ขั้นต่ำ/สูงสุด/สูงสุดต่อเลข',
        'route' => 'admin.lotto.bet_limits.index',
        'sort' => 7,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.reports',
        'name' => 'รายงาน Lotto',
        'route' => 'admin.lotto.reports.pending_bets',
        'sort' => 3,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.reports.pending_bets',
        'name' => 'รอผลเดิมพัน',
        'route' => 'admin.lotto.reports.pending_bets',
        'sort' => 1,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.reports.profit_loss_forecast',
        'name' => 'ดูของรวม/คาดคะเน ได้-เสีย',
        'route' => 'admin.lotto.reports.profit_loss_forecast',
        'sort' => 2,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.reports.member_bet_types',
        'name' => 'ดูของสมาชิก/ประเภท',
        'route' => 'admin.lotto.reports.member_bet_types',
        'sort' => 3,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.reports.tickets_cancel',
        'name' => 'รายการโพย/ยกเลิกโพย',
        'route' => 'admin.lotto.reports.tickets_cancel',
        'sort' => 4,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
    [
        'key' => 'lotto.reports.blocked_numbers',
        'name' => 'เลขปิดรับ/เลขอั้น',
        'route' => 'admin.lotto.reports.blocked_numbers',
        'sort' => 5,
        'icon-class' => 'fa-ticket',
        'badge' => 0,
        'badge-color' => 'badge-primary',
        'status' => 1,
    ],
];
