<?php

return [
    'default' => 'default',
    'required_token_keys' => [
        'surface-subtle',
        'surface-card',
        'surface-page',
        'surface-navbar',
        'surface-highlight',
        'brand-primary',
        'brand-primary-hover',
        'text-strong',
        'text-default',
        'text-muted',
        'border-default',
        'status-error',
        'status-success',
        'status-warning',
    ],
    'presets' => [
        'default' => [
            'name' => 'Default',
            'tokens' => [
                'surface-subtle' => '#edf1f6',
                'surface-card' => '#ffffff',
                'surface-page' => '#edf1f6',
                'surface-navbar' => 'rgba(255,255,255,0.96)',
                'surface-highlight' => '#0071e3',
                'brand-primary' => '#0071e3',
                'brand-primary-hover' => '#0077ed',
                'text-strong' => '#0f172a',
                'text-default' => '#334155',
                'text-muted' => '#64748b',
                'border-default' => 'rgba(15, 23, 42, 0.14)',
                'status-error' => '#ff3b30',
                'status-success' => '#34c759',
                'status-warning' => '#ff9500',
            ],
        ],
        'midnight' => [
            'name' => 'Midnight',
            'tokens' => [
                'surface-subtle' => '#1e293b',
                'surface-card' => '#0f172a',
                'surface-page' => '#020617',
                'surface-navbar' => 'rgba(15,23,42,0.92)',
                'surface-highlight' => '#f59e0b',
                'brand-primary' => '#fbbf24',
                'brand-primary-hover' => '#fcd34d',
                'text-strong' => '#f8fafc',
                'text-default' => '#cbd5e1',
                'text-muted' => '#94a3b8',
                'border-default' => 'rgba(241,245,249,0.12)',
                'status-error' => '#f87171',
                'status-success' => '#34d399',
                'status-warning' => '#fbbf24',
            ],
        ],
        'forest' => [
            'name' => 'Forest',
            'tokens' => [
                'surface-subtle' => '#f0fdf4',
                'surface-card' => '#ffffff',
                'surface-page' => '#ecfdf5',
                'surface-navbar' => 'rgba(240,253,244,0.96)',
                'surface-highlight' => '#15803d',
                'brand-primary' => '#15803d',
                'brand-primary-hover' => '#16a34a',
                'text-strong' => '#14532d',
                'text-default' => '#166534',
                'text-muted' => '#4d7c0f',
                'border-default' => 'rgba(20,83,45,0.14)',
                'status-error' => '#dc2626',
                'status-success' => '#15803d',
                'status-warning' => '#ca8a04',
            ],
        ],
    ],
];
