<?php

return [
    'default' => 'default',
    'required_token_keys' => [
        'surface-subtle',
        'surface-card',
        'surface-page',
        'surface-navbar',
        'surface-highlight',
        'brand-primary',
        'brand-primary-hover',
        'text-strong',
        'text-default',
        'text-muted',
        'border-default',
        'status-error',
        'status-success',
        'status-warning',
    ],
    'presets' => [
        'default' => [
            'name' => 'Default',
            'tokens' => [
                'surface-subtle' => '#edf1f6',
                'surface-card' => '#ffffff',
                'surface-page' => '#edf1f6',
                'surface-navbar' => 'rgba(255,255,255,0.96)',
                'surface-highlight' => '#0071e3',
                'brand-primary' => '#0071e3',
                'brand-primary-hover' => '#0077ed',
                'text-strong' => '#0f172a',
                'text-default' => '#334155',
                'text-muted' => '#64748b',
                'border-default' => 'rgba(15, 23, 42, 0.14)',
                'status-error' => '#ff3b30',
                'status-success' => '#34c759',
                'status-warning' => '#ff9500',
            ],
        ],
        'midnight' => [
            'name' => 'Midnight',
            'style' => 'ดาร์ก พื้นกรมท่า แอคเซนต์ทอง — เหมาะกับเว็บหวย VIP',
            'tokens' => [
                'surface-subtle' => '#1e293b',
                'surface-card' => '#0f172a',
                'surface-page' => '#020617',
                'surface-navbar' => 'rgba(15,23,42,0.92)',
                'surface-highlight' => '#f59e0b',
                'brand-primary' => '#fbbf24',
                'brand-primary-hover' => '#fcd34d',
                'text-strong' => '#f8fafc',
                'text-default' => '#cbd5e1',
                'text-muted' => '#94a3b8',
                'border-default' => 'rgba(241,245,249,0.12)',
                'status-error' => '#f87171',
                'status-success' => '#34d399',
                'status-warning' => '#fbbf24',
            ],
        ],
        'forest' => [
            'name' => 'Forest',
            'style' => 'เขียวสด - ดูเป็นเว็บการเงิน/แบงก์',
            'tokens' => [
                'surface-subtle' => '#f0fdf4',
                'surface-card' => '#ffffff',
                'surface-page' => '#ecfdf5',
                'surface-navbar' => 'rgba(240,253,244,0.96)',
                'surface-highlight' => '#15803d',
                'brand-primary' => '#15803d',
                'brand-primary-hover' => '#16a34a',
                'text-strong' => '#14532d',
                'text-default' => '#166534',
                'text-muted' => '#4d7c0f',
                'border-default' => 'rgba(20,83,45,0.14)',
                'status-error' => '#dc2626',
                'status-success' => '#15803d',
                'status-warning' => '#ca8a04',
            ],
        ],
        'platinum_casino' => [
            'name' => 'Platinum Casino',
            'style' => 'เทาแพลตินัมหรู — เหมาะกับคาสิโนพรีเมียม',
            'tokens' => [
                'surface-subtle' => '#374151',
                'surface-card' => '#1f2937',
                'surface-page' => '#111827',
                'surface-navbar' => 'rgba(31,41,55,0.92)',
                'surface-highlight' => '#9ca3af',
                'brand-primary' => '#e5e7eb',
                'brand-primary-hover' => '#f9fafb',
                'text-strong' => '#ffffff',
                'text-default' => '#d1d5db',
                'text-muted' => '#9ca3af',
                'border-default' => 'rgba(229,231,235,0.14)',
                'status-error' => '#f87171',
                'status-success' => '#34d399',
                'status-warning' => '#fbbf24',
            ],
        ],
        'ruby_slot' => [
            'name' => 'Ruby Slot',
            'style' => 'แดงทับทิม — เหมาะกับสล็อตแตกง่าย',
            'tokens' => [
                'surface-subtle' => '#881337',
                'surface-card' => '#4c0519',
                'surface-page' => '#19030b',
                'surface-navbar' => 'rgba(76,5,25,0.92)',
                'surface-highlight' => '#e11d48',
                'brand-primary' => '#fb7185',
                'brand-primary-hover' => '#fda4af',
                'text-strong' => '#fff1f2',
                'text-default' => '#fecdd3',
                'text-muted' => '#fda4af',
                'border-default' => 'rgba(251,113,133,0.18)',
                'status-error' => '#ef4444',
                'status-success' => '#4ade80',
                'status-warning' => '#facc15',
            ],
        ],
        'amber_fortune' => [
            'name' => 'Amber Fortune',
            'style' => 'ส้มทอง — เหมาะกับเว็บหวยโปรโมชันแรง',
            'tokens' => [
                'surface-subtle' => '#7c2d12',
                'surface-card' => '#431407',
                'surface-page' => '#1c0702',
                'surface-navbar' => 'rgba(67,20,7,0.92)',
                'surface-highlight' => '#f97316',
                'brand-primary' => '#fb923c',
                'brand-primary-hover' => '#fdba74',
                'text-strong' => '#fff7ed',
                'text-default' => '#fed7aa',
                'text-muted' => '#fdba74',
                'border-default' => 'rgba(251,146,60,0.16)',
                'status-error' => '#f87171',
                'status-success' => '#22c55e',
                'status-warning' => '#facc15',
            ],
        ],
        'galaxy_spin' => [
            'name' => 'Galaxy Spin',
            'style' => 'น้ำเงินม่วงอวกาศ — เหมาะกับสล็อตแฟนตาซี',
            'tokens' => [
                'surface-subtle' => '#3730a3',
                'surface-card' => '#1e1b4b',
                'surface-page' => '#09011f',
                'surface-navbar' => 'rgba(30,27,75,0.92)',
                'surface-highlight' => '#6366f1',
                'brand-primary' => '#8b5cf6',
                'brand-primary-hover' => '#a78bfa',
                'text-strong' => '#eef2ff',
                'text-default' => '#c7d2fe',
                'text-muted' => '#a5b4fc',
                'border-default' => 'rgba(139,92,246,0.2)',
                'status-error' => '#fb7185',
                'status-success' => '#34d399',
                'status-warning' => '#facc15',
            ],
        ],
        'thai_lottery_classic' => [
            'name' => 'Thai Lottery Classic',
            'style' => 'น้ำเงินแดงขาว — เหมาะกับเว็บหวยไทย',
            'tokens' => [
                'surface-subtle' => '#1e3a8a',
                'surface-card' => '#172554',
                'surface-page' => '#020617',
                'surface-navbar' => 'rgba(23,37,84,0.92)',
                'surface-highlight' => '#dc2626',
                'brand-primary' => '#2563eb',
                'brand-primary-hover' => '#60a5fa',
                'text-strong' => '#ffffff',
                'text-default' => '#dbeafe',
                'text-muted' => '#93c5fd',
                'border-default' => 'rgba(219,234,254,0.14)',
                'status-error' => '#ef4444',
                'status-success' => '#22c55e',
                'status-warning' => '#fbbf24',
            ],
        ],
        'black_diamond' => [
            'name' => 'Black Diamond',
            'style' => 'ดำหรูตัดฟ้า — เหมาะกับคาสิโนระดับสูง',
            'tokens' => [
                'surface-subtle' => '#1f2937',
                'surface-card' => '#111827',
                'surface-page' => '#000000',
                'surface-navbar' => 'rgba(17,24,39,0.94)',
                'surface-highlight' => '#0891b2',
                'brand-primary' => '#22d3ee',
                'brand-primary-hover' => '#67e8f9',
                'text-strong' => '#f8fafc',
                'text-default' => '#cbd5e1',
                'text-muted' => '#94a3b8',
                'border-default' => 'rgba(34,211,238,0.16)',
                'status-error' => '#f87171',
                'status-success' => '#34d399',
                'status-warning' => '#fbbf24',
            ],
        ],
        'royal_gold' => [
            'name' => 'Royal Gold',
            'style' => 'ดำทองหรู — เหมาะกับคาสิโน VIP',
            'tokens' => [
                'surface-subtle' => '#27272a',
                'surface-card' => '#18181b',
                'surface-page' => '#09090b',
                'surface-navbar' => 'rgba(24,24,27,0.92)',
                'surface-highlight' => '#ca8a04',
                'brand-primary' => '#facc15',
                'brand-primary-hover' => '#fde047',
                'text-strong' => '#fafafa',
                'text-default' => '#d4d4d8',
                'text-muted' => '#a1a1aa',
                'border-default' => 'rgba(250,250,250,0.12)',
                'status-error' => '#ef4444',
                'status-success' => '#22c55e',
                'status-warning' => '#facc15',
            ],
        ],
        'neon_vegas' => [
            'name' => 'Neon Vegas',
            'style' => 'ม่วงนีออน — เหมาะกับสล็อตออนไลน์',
            'tokens' => [
                'surface-subtle' => '#2e1065',
                'surface-card' => '#1e1b4b',
                'surface-page' => '#0f0529',
                'surface-navbar' => 'rgba(30,27,75,0.9)',
                'surface-highlight' => '#a855f7',
                'brand-primary' => '#d946ef',
                'brand-primary-hover' => '#f0abfc',
                'text-strong' => '#ffffff',
                'text-default' => '#e9d5ff',
                'text-muted' => '#c084fc',
                'border-default' => 'rgba(216,180,254,0.18)',
                'status-error' => '#fb7185',
                'status-success' => '#4ade80',
                'status-warning' => '#facc15',
            ],
        ],
        'lucky_emerald' => [
            'name' => 'Lucky Emerald',
            'style' => 'เขียวมรกต — เหมาะกับเว็บหวยสายมงคล',
            'tokens' => [
                'surface-subtle' => '#064e3b',
                'surface-card' => '#022c22',
                'surface-page' => '#011510',
                'surface-navbar' => 'rgba(2,44,34,0.92)',
                'surface-highlight' => '#10b981',
                'brand-primary' => '#34d399',
                'brand-primary-hover' => '#6ee7b7',
                'text-strong' => '#ecfdf5',
                'text-default' => '#a7f3d0',
                'text-muted' => '#6ee7b7',
                'border-default' => 'rgba(167,243,208,0.14)',
                'status-error' => '#f87171',
                'status-success' => '#22c55e',
                'status-warning' => '#fbbf24',
            ],
        ],
        'red_dragon' => [
            'name' => 'Red Dragon',
            'style' => 'แดงจีนทอง — เหมาะกับหวย VIP / คาสิโนเอเชีย',
            'tokens' => [
                'surface-subtle' => '#7f1d1d',
                'surface-card' => '#450a0a',
                'surface-page' => '#1c0505',
                'surface-navbar' => 'rgba(69,10,10,0.92)',
                'surface-highlight' => '#dc2626',
                'brand-primary' => '#fbbf24',
                'brand-primary-hover' => '#fde68a',
                'text-strong' => '#fff7ed',
                'text-default' => '#fecaca',
                'text-muted' => '#fca5a5',
                'border-default' => 'rgba(254,202,202,0.16)',
                'status-error' => '#fb7185',
                'status-success' => '#4ade80',
                'status-warning' => '#facc15',
            ],
        ],
        'ocean_jackpot' => [
            'name' => 'Ocean Jackpot',
            'style' => 'น้ำเงินฟ้า — เหมาะกับเว็บหวยทันสมัย',
            'tokens' => [
                'surface-subtle' => '#0c4a6e',
                'surface-card' => '#082f49',
                'surface-page' => '#020617',
                'surface-navbar' => 'rgba(8,47,73,0.92)',
                'surface-highlight' => '#0284c7',
                'brand-primary' => '#38bdf8',
                'brand-primary-hover' => '#7dd3fc',
                'text-strong' => '#f0f9ff',
                'text-default' => '#bae6fd',
                'text-muted' => '#7dd3fc',
                'border-default' => 'rgba(186,230,253,0.14)',
                'status-error' => '#f87171',
                'status-success' => '#34d399',
                'status-warning' => '#fbbf24',
            ],
        ],
        'cyber_lotto' => [
            'name' => 'Cyber Lotto',
            'style' => 'ไซเบอร์พังก์ ฟ้า-ชมพู — เหมาะกับเว็บหวยวัยรุ่น',
            'tokens' => [
                'surface-subtle' => '#312e81',
                'surface-card' => '#111827',
                'surface-page' => '#030712',
                'surface-navbar' => 'rgba(17,24,39,0.9)',
                'surface-highlight' => '#06b6d4',
                'brand-primary' => '#ec4899',
                'brand-primary-hover' => '#f472b6',
                'text-strong' => '#f9fafb',
                'text-default' => '#d1d5db',
                'text-muted' => '#9ca3af',
                'border-default' => 'rgba(236,72,153,0.2)',
                'status-error' => '#fb7185',
                'status-success' => '#22d3ee',
                'status-warning' => '#facc15',
            ],
        ],
        'pink_lucky' => [
            'name' => 'Pink Lucky',
            'style' => 'ชมพูสดใส — เหมาะกับเว็บหวยสายบันเทิง',
            'tokens' => [
                'surface-subtle' => '#831843',
                'surface-card' => '#500724',
                'surface-page' => '#1f0613',
                'surface-navbar' => 'rgba(80,7,36,0.92)',
                'surface-highlight' => '#db2777',
                'brand-primary' => '#f472b6',
                'brand-primary-hover' => '#f9a8d4',
                'text-strong' => '#fdf2f8',
                'text-default' => '#fbcfe8',
                'text-muted' => '#f9a8d4',
                'border-default' => 'rgba(244,114,182,0.18)',
                'status-error' => '#fb7185',
                'status-success' => '#4ade80',
                'status-warning' => '#facc15',
            ],
        ],
        'golden_temple' => [
            'name' => 'Golden Temple',
            'style' => 'น้ำตาลทองศักดิ์สิทธิ์ — เหมาะกับหวยมงคล',
            'tokens' => [
                'surface-subtle' => '#78350f',
                'surface-card' => '#451a03',
                'surface-page' => '#1c0a00',
                'surface-navbar' => 'rgba(69,26,3,0.92)',
                'surface-highlight' => '#d97706',
                'brand-primary' => '#f59e0b',
                'brand-primary-hover' => '#fbbf24',
                'text-strong' => '#fffbeb',
                'text-default' => '#fde68a',
                'text-muted' => '#fcd34d',
                'border-default' => 'rgba(245,158,11,0.18)',
                'status-error' => '#f87171',
                'status-success' => '#34d399',
                'status-warning' => '#fbbf24',
            ],
        ],
        'mint_jackpot' => [
            'name' => 'Mint Jackpot',
            'style' => 'เขียวมิ้นต์ดำ — เหมาะกับเว็บเกมออนไลน์ทันสมัย',
            'tokens' => [
                'surface-subtle' => '#134e4a',
                'surface-card' => '#042f2e',
                'surface-page' => '#021817',
                'surface-navbar' => 'rgba(4,47,46,0.92)',
                'surface-highlight' => '#14b8a6',
                'brand-primary' => '#2dd4bf',
                'brand-primary-hover' => '#5eead4',
                'text-strong' => '#f0fdfa',
                'text-default' => '#ccfbf1',
                'text-muted' => '#99f6e4',
                'border-default' => 'rgba(45,212,191,0.16)',
                'status-error' => '#f87171',
                'status-success' => '#22c55e',
                'status-warning' => '#facc15',
            ],
        ],
    ],
];
