<?php

return [
	[
		'key' => 'lotto',
		'name' => 'Lotto',
		'route' => 'admin.lotto.groups.index',
		'sort' => 87,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.groups',
		'name' => 'กลุ่มหวย',
		'route' => 'admin.lotto.groups.index',
		'sort' => 1,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.markets',
		'name' => 'รายการหวย',
		'route' => 'admin.lotto.markets.index',
		'sort' => 2,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.rate_plans',
		'name' => 'อัตราจ่าย',
		'route' => 'admin.lotto.rate_plans.index',
		'sort' => 3,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.default_settings',
		'name' => 'ค่าพื้นฐานหวย',
		'route' => 'admin.lotto.default_settings.index',
		'sort' => 4,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.member_permissions',
		'name' => 'สิทธิ์การเล่น',
		'route' => 'admin.lotto.member_permissions.index',
		'sort' => 5,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.member_rate_plans',
		'name' => 'อัตราจ่ายสมาชิก',
		'route' => 'admin.lotto.member_rate_plans.index',
		'sort' => 6,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.draws',
		'name' => 'งวดหวย',
		'route' => 'admin.lotto.draws.index',
		'sort' => 7,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.number_blocks',
		'name' => 'เลขอั้น',
		'route' => 'admin.lotto.number_blocks.index',
		'sort' => 8,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.tickets',
		'name' => 'รายการแทง',
		'route' => 'admin.lotto.tickets.index',
		'sort' => 9,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.exposure_report',
		'name' => 'รายงาน Exposure',
		'route' => 'admin.lotto.reports.exposure',
		'sort' => 10,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
	[
		'key' => 'lotto.revenue_report',
		'name' => 'รายงานรายได้',
		'route' => 'admin.lotto.reports.revenue',
		'sort' => 11,
		'icon-class' => 'fa-ticket',
		'badge' => 0,
		'badge-color' => 'badge-primary',
		'status' => 1,
	],
];
